spring.application.name=rentalTool-BackEnd


#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rentaltooldb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Data Initialization (opcjonalne - odkomentuj aby włączyć automatyczne ładowanie danych testowych)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

#rsa
rsa.rsa-private-key=classpath:certs/private.pem
rsa.rsa-public-key=classpath:certs/public.pem

# File storage configuration
file.upload-dir=./uploads/images

# Maximum file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger UI configuration
springdoc.swagger-ui.csrf.enabled=false
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# swagger-ui custom path
#springdoc.swagger-ui.path=/swagger-ui.html

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krolbartek14@gmail.com
spring.mail.password=ertf wtif yssl guhe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL (dla przyszłych funkcji)
app.frontend.url=http://localhost:4200

# Backend URL (dla linków weryfikacyjnych)
app.backend.url=http://localhost:8080